//! Cross-implementation vectors for placeholder substitution.
//!
//! The `substitution` section of the **shared golden fixture**
//! (`apps/run/testdata/vectors.json`, generated by its `gen-vectors.mts`) is the
//! one description of what `{{seekrit:NAME}}` means. This proxy is the reference
//! implementation; the `fetch` and `httpx` shims in the language SDKs run the
//! same cases against the same file, so the rules cannot drift apart between an
//! in-process shim and the proxy an operator eventually puts in front of it.
//!
//! Read straight from the canonical file rather than a copy in this crate's
//! `testdata/`: one fixture, nothing to keep in sync. Tests are not part of a
//! release build, so the path out of the crate never reaches a Docker context.

use std::collections::BTreeSet;

use seekrit_proxy::substitute::{substitute, Lookup, SubError};
use serde_json::Value;

fn cases() -> Vec<Value> {
    let raw = include_str!("../testdata/run-vectors.json");
    let v: Value = serde_json::from_str(raw).expect("vectors.json is valid JSON");
    v["substitution"]["cases"]
        .as_array()
        .expect("substitution.cases")
        .clone()
}

fn strings(case: &Value, key: &str) -> Vec<String> {
    case[key]
        .as_array()
        .map(|a| {
            a.iter()
                .map(|s| s.as_str().expect("string").to_string())
                .collect()
        })
        .unwrap_or_default()
}

/// The lookup the fixture's `note` prescribes: `denied` wins, then `values`,
/// then Unknown.
fn lookup_for(case: &Value) -> impl Fn(&str) -> Lookup + '_ {
    let denied: BTreeSet<String> = strings(case, "denied").into_iter().collect();
    move |name: &str| {
        if denied.contains(name) {
            return Lookup::Denied;
        }
        match case["values"].get(name).and_then(Value::as_str) {
            Some(value) => Lookup::Value(value.to_string()),
            None => Lookup::Unknown,
        }
    }
}

#[test]
fn every_substitution_vector_matches() {
    let cases = cases();
    assert!(!cases.is_empty(), "fixture carries substitution cases");

    for case in &cases {
        let name = case["name"].as_str().expect("case name");
        let input = case["input"].as_str().expect("case input");
        let lookup = lookup_for(case);
        let result = substitute(input.as_bytes(), &lookup);

        match case.get("error") {
            Some(expected) => {
                let want_code = expected["code"].as_str().expect("error.code");
                let want_name = expected["name"].as_str().expect("error.name");
                match result {
                    Err(SubError::Denied(got)) => {
                        assert_eq!(want_code, "denied", "{name}: wrong error kind");
                        assert_eq!(got, want_name, "{name}: wrong secret named");
                    }
                    Err(SubError::Unknown(got)) => {
                        assert_eq!(want_code, "unresolved", "{name}: wrong error kind");
                        assert_eq!(got, want_name, "{name}: wrong secret named");
                    }
                    Ok(outcome) => panic!(
                        "{name}: expected {want_code} for {want_name}, got {:?}",
                        String::from_utf8_lossy(&outcome.bytes)
                    ),
                }
            }
            None => {
                let outcome = result.unwrap_or_else(|e| panic!("{name}: unexpected refusal {e:?}"));
                let got = String::from_utf8(outcome.bytes).expect("utf-8 out");
                assert_eq!(got, case["expected"].as_str().expect("expected"), "{name}");
                let want: Vec<String> = strings(case, "names");
                let injected: Vec<String> = outcome.names.into_iter().collect();
                assert_eq!(injected, want, "{name}: injected names");
            }
        }
    }
}
